global:
  scrape_interval: 2s
  external_labels:
    monitor: 'node'
  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['65.0.11.184:9090']
    - job name: 'node-exporter'
      static_configs:
        - targets: ['65.0.11.184:9100']
